### ISSUE TITLE
Error: PostCSS plugin autoprefixer requires PostCSS 8.

### ISSUE THREAD

**Issue by motcodes** [dlexio/frontal.js#2]
I discoverd this error when chossing the basic and custom option.

Steps to reproduce:
1. `frontal init my-project`
2. then choose basic or custom.  
3. `cd my-project && frontal dev`

Then this error occurs:
![Screen Shot 2021-03-12 at 11 35 28](https://user-images.githubusercontent.com/20223529/110928322-0d000380-8327-11eb-8d3e-aee06f7e1bb4.png)

For this output I selected `custom` with `tailwindCss` and `Bable, PostCss, ESLint`.
The error occurs with or without PostCss.

**Comment by MohsenElgendy** [comment]
@motcodes thanks for reporting the issue, I've tried to reproduce it but I'm not getting the same error, if you may, could you share the `package.json` that was generated via the `frontal init` command along with the `package-lock.json` or `yarn.lock` so I can understand your dependencies graph further?

**Comment by motcodes** [comment]
The `package.json` and `yarn.lock` are in the zip.
Additional infos:
node: v14.15.5  
npm: v6.14.11
os: M1 Mac Mini - Big Sur 11.2.3

[packageJsonYarnLock.zip](https://github.com/dlexio/frontal.js/files/6131136/packageJsonYarnLock.zip)

**Comment by and-Zmei** [comment]
i have the same error

![image](https://user-images.githubusercontent.com/6105225/111023015-28c6e080-83df-11eb-8d75-ec37c125338a.png)

**Comment by MohsenElgendy** [comment]
@motcodes @and-Zmei I've pushed an update that I believe should fix the problem, could you update to `frontal@0.1.28` which is the latest version, and let me know guys if the problem still occurs? thanks for your patience.

**Comment by and-Zmei** [comment]
@MohsenElgendy 
very good, no more error, thanks
